# initiate deployment for simplenodeservice
---
-
  hosts: "{{ demo_host }}"
  name: "initiate deployment with Ansible"
  tasks:
    -
      name: "deploy - remove existing simplenodeservice container"
      docker_container:
        name: simplenodeservice
        state: absent
    -
      name: "deploy - run new simplenodeservice container"
      docker_container:
        name: simplenodeservice
        image: grabnerandi/simplenodeservice:2.0.2
        state: started
        ports:
         - "8080:8080"
    -
      name: "push Dynatrace custom deployment event"
      uri:
        url: "{{ dt_api_url }}/v1/events"
        method: POST
        headers:
          content-type: application/json
          Authorization: "Api-Token {{ dt_api_token }}"
        body:
          eventType: CUSTOM_DEPLOYMENT
          attachRules:
            tagRule:
            - meTypes:
              - SERVICE
              - PROCESS_GROUP_INSTANCE
              - HOST
              tags:
              - context: CONTEXTLESS
                key: "{{ deployment_tag_key }}"
                value: "{{ deployment_tag_value }}"
          source: Ansible Tower
          deploymentName: "SimpleNodeService"
          deploymentVersion: "2.0.2"
          remediationAction: "{{ deployment_remediation }}"
          customProperties:
            Details: "SimpleNodeService Deploy New Version"
            Version: "grabnerandi/simplenodeservice:2.0.2"
        body_format: json
        status_code: 200
